pipeline:
  name: sana-1.6b-1024px-bf16-ch5632
  path: Lawrence-cj/Sana_1600M_1024px_BF16_diffusers_ch5632
  dtype: torch.bfloat16
eval:
  num_steps: 20
  guidance_scale: 4.5
  protocol: flowdpm{num_steps}-g{guidance_scale}
quant:
  calib:
    batch_size: 256
  wgts:
    calib_range:
      element_batch_size: 64
      sample_batch_size: 32
      element_size: 512
      sample_size: -1
    low_rank:
      sample_batch_size: 32
      sample_size: -1
    skips: 
    - embed
    - resblock_shortcut
    - resblock_time_proj
    - transformer_proj_in
    - transformer_proj_out
    - transformer_norm
    - transformer_add_norm
    - attn_add
    - ffn_add
    - down_sample
    - up_sample
  ipts:
    calib_range:
      element_batch_size: 64
      sample_batch_size: 32
      element_size: 512
      sample_size: -1
    skips: 
    - embed
    - resblock_shortcut
    - resblock_time_proj
    - transformer_proj_in
    - transformer_proj_out
    - transformer_norm
    - transformer_add_norm
    - attn_add
    - ffn_add
    - down_sample
    - up_sample
  opts:
    calib_range:
      element_batch_size: 64
      sample_batch_size: 32
      element_size: 512
      sample_size: -1
  smooth:
    proj:
      element_batch_size: -1
      sample_batch_size: 32
      element_size: -1
      sample_size: -1
    attn:
      sample_batch_size: 32
      sample_size: -1
